### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by fredfortier** [linuxserver/docker-firefox#10]
This is probably a user issue but I couldn't work out the local clipboard. Any pointers would be appreciated.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
```
❯ uname -a
Linux 5.15.35-1-lts x86_64 unknown unknown GNU/Linux
```

**Browser**
```
❯ brave --version
Brave Browser 100.1.37.116
```

```yaml
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - $HOME/.config/firefox:/config:rw
    shm_size: "2gb"
    restart: unless-stopped
    network_mode: service:wireguard
    depends_on:
      - wireguard
```
