### ISSUE TITLE
File action "delete" in Guacamole menu does not work: "socket.io.js could not be loaded"

### ISSUE THREAD

**Issue by ch4ox** [linuxserver/docker-firefox#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I'm trying to delete a downloaded file. For this I'm opening the Guacamole menu (reachable on the left side or by using the shortcut Ctrl+Alt+Shift), then there's "Files" which will give me a file browser to download, upload, delete my files. When selecting a previously downloaded file and clicking on "Delete" it should delete the file.

## Current Behavior

A new warning icon appears which says "file /files/socket.io/socket.io.js could not be loaded".

## Steps to Reproduce

1. Install linuxserver/docker-firefox with default settings (I used docker-compose)
2. Open up the application on http://*:3000, download a file with Firefox and save it to /config/Downloads/
3. Hit Ctrl+Alt+Shift, click on "Files", navigate to /config/Downloads/ and right click on the downloaded file.
4. Click "Delete".

![screenshot_1](https://user-images.githubusercontent.com/92687457/137639250-23d0665b-a862-48ac-8fbc-20e6f18b3d67.png)

![screenshot_2](https://user-images.githubusercontent.com/92687457/137639258-5aeecd88-a2ad-4a94-9cf2-6d07ffcabb5e.png)

![screenshot_3](https://user-images.githubusercontent.com/92687457/137639262-efeac16d-2779-4efd-a5f5-5bf9de934a17.png)

## Environment
**OS:** Ubuntu 20.04 LTS
**CPU architecture:** x64
**How docker service was installed:**

installed from official distro repository:
apt install docker-ce docker-compose

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml:
```
version: '2.2'

services:
  firefox:
    image: linuxserver/firefox
    container_name: firefox
    environment:
      - "TZ=Europe/Berlin"
      - "PUID=33"  # www-data
      - "PGID=33"  # www-data
      - "DOCKER_MODS=linuxserver/mods:firefox-fonts"
    shm_size: '2gb'
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./_data:/config"
```

## Docker logs

see attached file logs.txt
[logs.txt](https://github.com/linuxserver/docker-firefox/files/7360580/logs.txt)
